# 2.2.1 创建tensor

In [1]:
import torch

In [2]:
x = torch.empty(5, 3) # 创建一个未初始化的tensor
print(x)

tensor([[8.7245e-39, 1.0286e-38, 9.0919e-39],
        [9.0919e-39, 9.2755e-39, 8.7245e-39],
        [9.4592e-39, 9.6429e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [4.1328e-39, 5.1429e-39, 1.0286e-38]])


In [3]:
x = torch.rand(5, 3) # 创建一个随机初始化的tensor
print(x)

tensor([[0.2237, 0.7459, 0.5001],
        [0.0650, 0.5876, 0.4005],
        [0.9533, 0.0064, 0.4559],
        [0.3028, 0.4421, 0.8610],
        [0.2507, 0.0220, 0.5657]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long) # 创建一个long型全0的tensor
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3]) # 根据数据创建
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.float64) # 返回的tensor有相同的dtype
print(x)

x = torch.randn_like(x, dtype=torch.float) # 通过现有的tensor创建
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0709, -0.8734, -0.9883],
        [ 0.5153, -1.4923,  0.0804],
        [-1.0559, -0.4328, -0.0104],
        [ 0.5882,  0.8566, -0.8835],
        [-0.1134, -0.0289,  2.0097]])


In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


# 2.2.2 操作

In [8]:
# 多种加法操作
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result) # 指定输出
print(result)

y.add_(x)
print(y)

tensor([[ 1.7121, -0.8198, -0.8699],
        [ 0.8192, -0.6845,  0.6859],
        [-0.4000, -0.3354,  0.5253],
        [ 0.8644,  1.0909, -0.8279],
        [ 0.3728,  0.0367,  2.9263]])
tensor([[ 1.7121, -0.8198, -0.8699],
        [ 0.8192, -0.6845,  0.6859],
        [-0.4000, -0.3354,  0.5253],
        [ 0.8644,  1.0909, -0.8279],
        [ 0.3728,  0.0367,  2.9263]])
tensor([[ 1.7121, -0.8198, -0.8699],
        [ 0.8192, -0.6845,  0.6859],
        [-0.4000, -0.3354,  0.5253],
        [ 0.8644,  1.0909, -0.8279],
        [ 0.3728,  0.0367,  2.9263]])
tensor([[ 1.7121, -0.8198, -0.8699],
        [ 0.8192, -0.6845,  0.6859],
        [-0.4000, -0.3354,  0.5253],
        [ 0.8644,  1.0909, -0.8279],
        [ 0.3728,  0.0367,  2.9263]])


In [9]:
# 索引
y = x[0, :] # 索引出来的结果与原数据共享内存
print(y)
y += 1
print(y)
print(x[0, :]) # 原数据也被修改

tensor([ 1.0709, -0.8734, -0.9883])
tensor([2.0709, 0.1266, 0.0117])
tensor([2.0709, 0.1266, 0.0117])


In [12]:
# 改变形状
y = x.view(15) 
z = x.view(-1, 5) # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

# view返回的新tensor也是共享data的
x += 1
print(x)
print(y)

print("使用clone返回一个真正的新的副本，不共享内存")
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])
tensor([[4.0709, 2.1266, 2.0117],
        [2.5153, 0.5077, 2.0804],
        [0.9441, 1.5672, 1.9896],
        [2.5882, 2.8566, 1.1165],
        [1.8866, 1.9711, 4.0097]])
tensor([4.0709, 2.1266, 2.0117, 2.5153, 0.5077, 2.0804, 0.9441, 1.5672, 1.9896,
        2.5882, 2.8566, 1.1165, 1.8866, 1.9711, 4.0097])
使用clone返回一个真正的新的副本，不共享内存
tensor([[ 3.0709,  1.1266,  1.0117],
        [ 1.5153, -0.4923,  1.0804],
        [-0.0559,  0.5672,  0.9896],
        [ 1.5882,  1.8566,  0.1165],
        [ 0.8866,  0.9711,  3.0097]])
tensor([4.0709, 2.1266, 2.0117, 2.5153, 0.5077, 2.0804, 0.9441, 1.5672, 1.9896,
        2.5882, 2.8566, 1.1165, 1.8866, 1.9711, 4.0097])


In [13]:
print("使用item()把标量tensor转化为一个python number")
x = torch.randn(1)
print(x)
print(x.item())

使用item()把标量tensor转化为一个python number
tensor([-1.5403])
-1.5402889251708984


# 2.2.3 广播机制

In [14]:
print("对于形状不同的两个tensor，先适当复制元素使他们形状相同再按元素运算")
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

对于形状不同的两个tensor，先适当复制元素使他们形状相同再按元素运算
tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


# 2.2.4 运算的内存开销

In [15]:
print("使用id来判断是否新开辟内存")
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id_before == id(y))

使用id来判断是否新开辟内存
False


In [16]:
print("使用索引把结果写回原来的内存")
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id_before == id(y))

使用索引把结果写回原来的内存
True


In [18]:
print("使用自加运算+=(add_())、out参数能达到同样效果")
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y+=x  y.add_(x)
print(id(y) == id_before)

使用自加运算+=(add_())、out参数能达到同样效果
True


# 2.2.5 Tensor与Numpy相互转换

In [19]:
print("使用 numpy() 或 from_numpy() 将 tensor 和 Numpy 中的数组相互转换，产生的数组共享内存，一个变，另一个也会变；使用 torch.tensor() 转换 numpy 数据会进行数据拷贝，返回值不再共享内存")

使用 numpy() 或 from_numpy() 将 tensor 和 Numpy 中的数组相互转换，产生的数组共享内存，一个变，另一个也会变；使用 torch.tensor() 转换 numpy 数据会进行数据拷贝，返回值不再共享内存


In [20]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a , b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [21]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [22]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# 2.2.6 Tensor on GPU

In [24]:
print("使用to()方法将tensor在CPU和GPU之间相互移动")
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
else:
    print("但是我买不起GPU")

使用to()方法将tensor在CPU和GPU之间相互移动
但是我买不起GPU
